### ISSUE TITLE
some filenames with special characters like ( ) etc. are causing trouble with curlew 

### ISSUE THREAD

**Issue by fastrizwaan** [chamfay/Curlew#10]
when I tried to convert this file:

Jaguar Attacks Crocodile (EXCLUSIVE VIDEO).mp4

it won't work.

but renaming and removing ( ) to say jaguar.mp4 curlew can work.

bash seems to be complaining.

**Comment by chamfay** [comment]
I've tried converting a file contain many special characters without problem :)
http://store6.up-00.com/2017-05/149371115765751.png

Thank you.
