### ISSUE TITLE
مشكلة ترخيص

### ISSUE THREAD

**Issue by alimiracle** [chamfay/Curlew#29]
مرحبً
رخصة وقف التي تستخدم في برنامجكم الجميل تتعارض مع رخصة جنو العامة (gpl)
و ب الاخص الحرية رقم 0
و تنص ايضً ان لايمكن لغير المسلم استخدام البرنامج بسبب استخدام عبارة  " مبادء الاسلام " 
فكما تعلم ان انتكون مسلم هو احد مبادء الاسلامم
ف ارجو حل المشكلة في اقرب وقت

**Comment by chamfay** [comment]
السلام عليكم،

لا يمكنني وضع رخصة للبرنامج خلاف رخصة **وقف** على الأقل في الوقت الحالي، حيث لا توجد رخصة تفي بالغرض بما فيها رخصة GPL
وأنا أريد أن اتبرأ أمام الله من استخدام برنامجي فيما يخالف تعاليم الإسلام الحنيف، كما أني لا أمانع من أن يستخدم برنامجي غير المسلم لكن في حدود ما ذكرت سابقا.

بالنسبة للتعارض أعلم ذلك ولقد ناقشت ذلك هنا: [http://www.linuxac.org/forum/threads/72518-%D8%B1%D8%AE%D8%B5%D8%A9-%D9%88%D9%82%D9%81-%D8%A5%D9%84%D9%89-%D8%A3%D9%8A%D9%86%D8%9F-%D9%88%D8%A7%D9%84%D8%A8%D8%B1%D8%A7%D9%85%D8%AC-%D8%A7%D9%84%D9%85%D8%B1%D8%AE%D8%B5%D8%A9-%D8%A8%D9%87%D8%A7](url)

كما يمكنك مراسلة أصحاب الرخصة.

عذرا على الإطالة، بالتوفيق.
