### ISSUE TITLE
Segmentation fault when click the license link

### ISSUE THREAD

**Issue by gtkraim** [chamfay/Curlew#30]
السلام عليكم
يحدث خطأ (Segmentation fault)
عند فتح "حول البرنامج" ثم "الرخصة" ثم النقر على رابط الرخصة ويتم غلق البرنامج

Hello
An error (Segmentation fault) occurs when open "about the program," and "license" tab then clicking  to license link.

Best wishes

**Comment by chamfay** [comment]
عذرًا على التأخير.
البرنامج يعمل عندي بصورة جيدة (استعمل KDE Neon، Ubuntu 16.10 Gnome)
ربما تكون الشكلة في إصدارة مكتبة GTK لديك.
