### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by lachhebo** [chamfay/Curlew#41]
Hello,

You should distribute your application as a flatpak. It would allow many users to install it on a easier and secure way.

**Comment by ghost** [comment]
I follow this request and also a snap package on snapcraft should be a very appreciated fact.

**Comment by coverme76** [comment]
@rm-root would you please add it to the well-doin' [community forum](https://forum.snapcraft.io/t/snap-wishlist-suggestions-wanted/567/252), then #?

chafrey hav talked to #[blamepopey](http://amzn.eu/8MmQvXI) before :+1: 

pura vida.
